### ISSUE TITLE
Check functionality using the paraview bundle included with openfoam

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-paraview#21]

**Comment by stefanoborini** [comment]
Please note, I am checking only the source build. Installing the extension with the docker image is hard due to the fact that the image contains pretty much no utilities of any kind.

**Comment by stefanoborini** [comment]
Ok, here are my findings on this regard.

openFoam binary distribution is shipped as a docker image. The paraview provided is 5.0.1.
Downloading the sources (specifically the third party libraries), there are two scripts to perform the paraview build: makeParaView and makeParaView3. It turns out that both script build 5.0.1 anyway, the problem being a variable ($ParaView_VERSION) which is set to 5.0.1 explicitly. To compile 3.14, the sources must be downloaded separately. 

I already verified that everything works with 3.14 manually compiled, but it is of my understanding that paraview 5 is not supported by our code. Is it a requirement to support the 5.x series (or any non 3.x series)? If so, I need to adapt our code to 5.x API. 

I close this issue because it eventually becomes a separate "Support paraview 5.x", but I need feedback on the topic @itziakos .

**Comment by itziakos** [comment]
Yes, I agree adding support for paraview 5 is in the feature request area for a future milestone
